 DROP TABLE IF EXISTS Players;

CREATE TABLE Players (
    Id TEXT PRIMARY KEY,
    Username TEXT UNIQUE NOT NULL,
    Data TEXT NOT NULL
);

INSERT INTO Players (Id, Username, Data)
VALUES (
    '1',
    'Guest',
    '{
      "Level": 16,
      "Experience": 235,
      "MaxHealth": 400,
      "Attack": 40,
      "Defense": 15,
      "Speed": 25,
      "Dexterity": 25,
      "Vitality": 25,
      "Wisdom": 25,
      "ToolbeltSize": 3,
      "Equipment": [
        { "ItemId": 1, "DataId": "weapon_double_staff", "CurrentTier": 1, "MaxTier": 1, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] }
      ],
      "Toolbelt": [
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] }
      ],
      "Stash": [
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] }
      ]
    }'
);

INSERT INTO Players (Id, Username, Data)
VALUES (
    '2',
    'Guest2',
    '{
      "Level": 20,
      "Experience": 235,
      "MaxHealth": 400,
      "Attack": 40,
      "Defense": 15,
      "Speed": 25,
      "Dexterity": 25,
      "Vitality": 25,
      "Wisdom": 25,
      "ToolbeltSize": 3,
      "Equipment": [
        { "ItemId": 1, "DataId": "weapon_basic_staff", "CurrentTier": 1, "MaxTier": 1, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] }
      ],
      "Toolbelt": [
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] }
      ],
      "Stash": [
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] },
        { "ItemId": 0, "DataId": "", "CurrentTier": 0, "MaxTier": 0, "SelectedPerkIds": [] }
      ]
    }'
);
